apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ld-server
  annotations:
    kubernetes.io/ingress.global-static-ip-name: finngen-api
  labels:
    app: ld-server
spec:
  rules:
  - host: api.finngen.fi
    http:
      paths:
      - backend:
          serviceName: ld-server
          servicePort: 80
        path: /*
---
apiVersion: v1
kind: Service
metadata:
  name: ld-server
  labels:
    app: ld-server
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: ld-server
    tier: web
